import Head from "next/head";
import { Inter } from "next/font/google";
import HomePage from "@/components/Modules/HomePage";
import MainLayouts from "@/components/Layouts/MainLayout";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    // <>
    //   <Head>
    //     <title>Rt Home Page</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <meta name="viewport" content="width=device-width, initial-scale=1" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   <main>
    //     <HomePage />{" "}
    //   </main>
    // </>
    <MainLayouts title={"rt home page"} description={"Home page"}>
      <HomePage />
    </MainLayouts>
  );
}
